#!/usr/bin/env sh
#Launch a 42school/engineering-bay service in two replicas and make sure that the service works properly (see the documentation provided at hub.docker.com). This service will be named engineering-bay and will be on the overmind network.
docker service create --name engineering-bay --network overmind --replicas 2 --env OC_USERNAME=user --env OC_PASSWD=password 42school/engineering-bay
