#!/usr/bin/env sh
#... Damn it, a group of zergs is attacking orbital-command, and shutting down the engineering-bay service won’t help at all... You must send a troup of Marines to eliminate the intruders. Launch a 42school/marine-squad in two replicas, and make sure that the service works properly (see the documentation provided at hub.docker.com). This service will be named... marines and will be on the overmind network.
docker service create --name marines --replicas 2 --network overmind --env OC_USERNAME=user --env OC_PASSWD=password 42school/marine-squad
